export const ecosystem = {
  name: "myecosystem",
  quality: {
    Complexity: {
      main: 9,
      min: 0,
      max: 10,
      best: "min",
    },
    Understandability: {
      main: 5,
      min: 0,
      max: 10,
      best: "max",
    },
    Coverage: {
      main: 3,
      min: 0,
      max: 10,
      best: "max",
    },
    Maintanability: {
      main: 4,
      min: 0,
      max: 10,
      best: "min",
    },
  },
};

export const links = [
  {
    source: "smach.ecore",
    target: "ros.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "log.ecore",
    target: "store.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "ETMap.ecore",
    target: "ETPhys.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "ETMap.ecore",
    target: "Room.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "Feature.ecore",
    target: "ontology.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "Feature.ecore",
    target: "identification.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "Feature.ecore",
    target: "evidence.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "Feature.ecore",
    target: "value.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "property.ecore",
    target: "Publication.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "property.ecore",
    target: "organization.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "property.ecore",
    target: "Feature.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "property.ecore",
    target: "identification.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "property.ecore",
    target: "ontology.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "Publication.ecore",
    target: "organization.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "Publication.ecore",
    target: "Feature.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "Publication.ecore",
    target: "ontology.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "Publication.ecore",
    target: "identification.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "etricegen.ecore",
    target: "Room.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "customer.ecore",
    target: "XMLType",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "store.ecore",
    target: "log.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "Petrinetv2.ecore",
    target: "Petrinetv1.ecore",
    type: "unidirectional",
    relationtype: "Distance",
    value: "75.0",
  },
  {
    source: "Petrinetv2.ecore",
    target: "Petrinetv3.ecore",
    type: "unidirectional",
    relationtype: "Distance",
    value: "100.0",
  },
  {
    source: "DB.ecore",
    target: "customer.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "DB.ecore",
    target: "XMLType",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "system.ecore",
    target: "operation.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "system.ecore",
    target: "process.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "Petrinetv1.ecore",
    target: "Petrinetv2.ecore",
    type: "unidirectional",
    relationtype: "Distance",
    value: "87.0",
  },
  {
    source: "Petrinetv1.ecore",
    target: "Petrinetv3.ecore",
    type: "unidirectional",
    relationtype: "Distance",
    value: "87.0",
  },
  {
    source: "ros.ecore",
    target: "smach.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "Petrinetv3.ecore",
    target: "Petrinetv2.ecore",
    type: "unidirectional",
    relationtype: "Distance",
    value: "83.0",
  },
  {
    source: "workbench.ecore",
    target: "wikicontent.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "derivedModel.ecore",
    target: "operation.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "derivedModel.ecore",
    target: "system.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "derivedModel.ecore",
    target: "process.ecore",
    type: "unidirectional",
    relationtype: "Dependency",
    value: "",
  },
  {
    source: "sigcomponents-model5.model",
    target: "sigocmponentsMMv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "personsList.model",
    target: "PersonList.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "persons.model",
    target: "PersonList.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "conferences_v5.model",
    target: "conferenceV1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "sigocmponentsMMv1_example2.model",
    target: "sigocmponentsMMv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "signcomponents1_v1.model",
    target: "sigocmponentsMMv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "tasks5_v1.model",
    target: "tasksv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "tasks4_v1.model",
    target: "tasksv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "sigcomponents-model3.model",
    target: "sigocmponentsMMv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "conferences_v1.model",
    target: "conferenceV1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "conferences_v3.model",
    target: "conferenceV1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "sigcomponents-model1.model",
    target: "sigocmponentsMMv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "sigocmponentsMMv1_example4.model",
    target: "sigocmponentsMMv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "conferences_v4.model",
    target: "conferenceV1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "tasks2_v1.model",
    target: "tasksv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "tasks3_v1.model",
    target: "tasksv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "sigocmponentsMMv1_example3.model",
    target: "sigocmponentsMMv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "sigcomponents-model4.model",
    target: "sigocmponentsMMv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "sigocmponentsMMv1_example1.model",
    target: "sigocmponentsMMv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "conferences1_v1.model",
    target: "conferenceV1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "conferences_v2.model",
    target: "conferenceV1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "sigocmponentsMMv1_example5.model",
    target: "sigocmponentsMMv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "sigcomponents-model2.model",
    target: "sigocmponentsMMv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "tasksv1_example1.model",
    target: "tasksv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "conferences4_v1.model",
    target: "conferenceV1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "conferences_v1_example4.model",
    target: "conferenceV1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "conferences5_v1.model",
    target: "conferenceV1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "task4.model",
    target: "tasksv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "fb.model",
    target: "SocialNetwork.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "tasksv1_example3.model",
    target: "tasksv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "conferences_v1_example2.model",
    target: "conferenceV1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "signcomponents2_v1.model",
    target: "sigocmponentsMMv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "signcomponents3_v1.model",
    target: "sigocmponentsMMv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "task2.model",
    target: "tasksv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "tasksv1_example5.model",
    target: "tasksv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "task5.model",
    target: "tasksv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "tasksv1_example2.model",
    target: "tasksv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "signcomponents5_v1.model",
    target: "sigocmponentsMMv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "signcomponents4_v1.model",
    target: "sigocmponentsMMv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "conferences_v1_example5.model",
    target: "conferenceV1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "task3.model",
    target: "tasksv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "conferences3_v1.model",
    target: "conferenceV1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "conferences2_v1.model",
    target: "conferenceV1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "conferences_v1_example1.model",
    target: "conferenceV1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "tasksv1_example4.model",
    target: "tasksv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "tasks1_v1.model",
    target: "tasksv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "conferences_v1_example3.model",
    target: "conferenceV1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
  {
    source: "task1.model",
    target: "tasksv1.ecore",
    type: "unidirectional",
    relationtype: "Conformance",
    value: "",
  },
];

export const nodes = {
  "smach.ecore": {
    name: "smach.ecore",
    type: "Metamodel",
    info: "smach.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "21.0",
      Understandability: "1.3809523582458496",
    },
  },
  "tasksv1.ecore": {
    name: "tasksv1.ecore",
    type: "Metamodel",
    info: "tasksv1.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "7.0",
      Understandability: "1.2857142686843872",
    },
  },
  "log.ecore": {
    name: "log.ecore",
    type: "Metamodel",
    info: "log.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "25.0",
      Understandability: "1.9199999570846558",
    },
  },
  "process.ecore": {
    name: "process.ecore",
    type: "Metamodel",
    info: "process.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "5.0",
      Understandability: "2.200000047683716",
    },
  },
  "ETMap.ecore": {
    name: "ETMap.ecore",
    type: "Metamodel",
    info: "ETMap.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "5.0",
      Understandability: "1.0",
    },
  },
  "Feature.ecore": {
    name: "Feature.ecore",
    type: "Metamodel",
    info: "Feature.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "4.0",
      Understandability: "2.75",
    },
  },
  "property.ecore": {
    name: "property.ecore",
    type: "Metamodel",
    info: "property.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "24.0",
      Understandability: "4.041666507720947",
    },
  },
  "wikicontent.ecore": {
    name: "wikicontent.ecore",
    type: "Metamodel",
    info: "wikicontent.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "4.0",
      Understandability: "1.0",
    },
  },
  "Publication.ecore": {
    name: "Publication.ecore",
    type: "Metamodel",
    info: "Publication.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "17.0",
      Understandability: "4.470588207244873",
    },
  },
  "ETPhys.ecore": {
    name: "ETPhys.ecore",
    type: "Metamodel",
    info: "ETPhys.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "8.0",
      Understandability: "1.0",
    },
  },
  "Room.ecore": {
    name: "Room.ecore",
    type: "Metamodel",
    info: "Room.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "82.0",
      Understandability: "2.0731706619262695",
    },
  },
  "etricegen.ecore": {
    name: "etricegen.ecore",
    type: "Metamodel",
    info: "etricegen.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "18.0",
      Understandability: "1.7777777910232544",
    },
  },
  "sigocmponentsMMv1.ecore": {
    name: "sigocmponentsMMv1.ecore",
    type: "Metamodel",
    info: "sigocmponentsMMv1.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "3.0",
      Understandability: "1.0",
    },
  },
  "customer.ecore": {
    name: "customer.ecore",
    type: "Metamodel",
    info: "customer.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "7.0",
      Understandability: "1.2857142686843872",
    },
  },
  "My.ecore": {
    name: "My.ecore",
    type: "Metamodel",
    info: "My.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "8.0",
      Understandability: "1.5",
    },
  },
  "conferenceV1.ecore": {
    name: "conferenceV1.ecore",
    type: "Metamodel",
    info: "conferenceV1.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "6.0",
      Understandability: "1.3333333730697632",
    },
  },
  "store.ecore": {
    name: "store.ecore",
    type: "Metamodel",
    info: "store.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "55.0",
      Understandability: "1.218181848526001",
    },
  },
  "Petrinetv2.ecore": {
    name: "Petrinetv2.ecore",
    type: "Metamodel",
    info: "Petrinetv2.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "4.0",
      Understandability: "1.0",
    },
  },
  "Features.ecore": {
    name: "Features.ecore",
    type: "Metamodel",
    info: "Features.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "2.0",
      Understandability: "1.0",
    },
  },
  "DB.ecore": {
    name: "DB.ecore",
    type: "Metamodel",
    info: "DB.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "5.0",
      Understandability: "1.2000000476837158",
    },
  },
  "system.ecore": {
    name: "system.ecore",
    type: "Metamodel",
    info: "system.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "5.0",
      Understandability: "1.7999999523162842",
    },
  },
  "PersonList.ecore": {
    name: "PersonList.ecore",
    type: "Metamodel",
    info: "PersonList.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "3.0",
      Understandability: "1.0",
    },
  },
  "Petrinetv1.ecore": {
    name: "Petrinetv1.ecore",
    type: "Metamodel",
    info: "Petrinetv1.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "3.0",
      Understandability: "1.0",
    },
  },
  "ros.ecore": {
    name: "ros.ecore",
    type: "Metamodel",
    info: "ros.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "21.0",
      Understandability: "1.3809523582458496",
    },
  },
  "Petrinetv3.ecore": {
    name: "Petrinetv3.ecore",
    type: "Metamodel",
    info: "Petrinetv3.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "4.0",
      Understandability: "1.0",
    },
  },
  "workbench.ecore": {
    name: "workbench.ecore",
    type: "Metamodel",
    info: "workbench.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "2.0",
      Understandability: "1.0",
    },
  },
  "SocialNetwork.ecore": {
    name: "SocialNetwork.ecore",
    type: "Metamodel",
    info: "SocialNetwork.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "5.0",
      Understandability: "1.399999976158142",
    },
  },
  "task.ecore": {
    name: "task.ecore",
    type: "Metamodel",
    info: "task.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "14.0",
      Understandability: "2.2857143878936768",
    },
  },
  "derivedModel.ecore": {
    name: "derivedModel.ecore",
    type: "Metamodel",
    info: "derivedModel.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "7.0",
      Understandability: "1.5714285373687744",
    },
  },
  "SqlDSL.ecore": {
    name: "SqlDSL.ecore",
    type: "Metamodel",
    info: "SqlDSL.ecore",
    virtual: "concrete",
    quality: {
      Complexity: "14.0",
      Understandability: "1.5",
    },
  },
  "ontology.ecore": {
    name: "ontology.ecore",
    type: "Metamodel",
    info: "ontology.ecore",
    virtual: "virtual",
    quality: {},
  },
  "identification.ecore": {
    name: "identification.ecore",
    type: "Metamodel",
    info: "identification.ecore",
    virtual: "virtual",
    quality: {},
  },
  "evidence.ecore": {
    name: "evidence.ecore",
    type: "Metamodel",
    info: "evidence.ecore",
    virtual: "virtual",
    quality: {},
  },
  "value.ecore": {
    name: "value.ecore",
    type: "Metamodel",
    info: "value.ecore",
    virtual: "virtual",
    quality: {},
  },
  "organization.ecore": {
    name: "organization.ecore",
    type: "Metamodel",
    info: "organization.ecore",
    virtual: "virtual",
    quality: {},
  },
  XMLType: {
    name: "XMLType",
    type: "Metamodel",
    info: "XMLType",
    virtual: "virtual",
    quality: {},
  },
  "operation.ecore": {
    name: "operation.ecore",
    type: "Metamodel",
    info: "operation.ecore",
    virtual: "virtual",
    quality: {},
  },
  "sigcomponents-model5.model": {
    name: "sigcomponents-model5.model",
    type: "Model",
    info: "sigcomponents-model5.model",
    virtual: "concrete",
    quality: {
      Complexity: "10.0",
      Coverage: "1.0",
    },
  },
  "personsList.model": {
    name: "personsList.model",
    type: "Model",
    info: "personsList.model",
    virtual: "concrete",
    quality: {
      Complexity: "5.0",
      Coverage: "0.3888888955116272",
    },
  },
  "persons.model": {
    name: "persons.model",
    type: "Model",
    info: "persons.model",
    virtual: "concrete",
    quality: {
      Complexity: "6.0",
      Coverage: "0.7777777910232544",
    },
  },
  "conferences_v5.model": {
    name: "conferences_v5.model",
    type: "Model",
    info: "conferences_v5.model",
    virtual: "concrete",
    quality: {
      Complexity: "13.0",
      Coverage: "0.9750000238418579",
    },
  },
  "sigocmponentsMMv1_example2.model": {
    name: "sigocmponentsMMv1_example2.model",
    type: "Model",
    info: "sigocmponentsMMv1_example2.model",
    virtual: "concrete",
    quality: {
      Complexity: "9.0",
      Coverage: "1.0",
    },
  },
  "signcomponents1_v1.model": {
    name: "signcomponents1_v1.model",
    type: "Model",
    info: "signcomponents1_v1.model",
    virtual: "concrete",
    quality: {
      Complexity: "5.0",
      Coverage: "1.0",
    },
  },
  "tasks5_v1.model": {
    name: "tasks5_v1.model",
    type: "Model",
    info: "tasks5_v1.model",
    virtual: "concrete",
    quality: {
      Complexity: "65.0",
      Coverage: "0.9166666865348816",
    },
  },
  "tasks4_v1.model": {
    name: "tasks4_v1.model",
    type: "Model",
    info: "tasks4_v1.model",
    virtual: "concrete",
    quality: {
      Complexity: "65.0",
      Coverage: "0.9166666865348816",
    },
  },
  "sigcomponents-model3.model": {
    name: "sigcomponents-model3.model",
    type: "Model",
    info: "sigcomponents-model3.model",
    virtual: "concrete",
    quality: {
      Complexity: "7.0",
      Coverage: "1.0",
    },
  },
  "conferences_v1.model": {
    name: "conferences_v1.model",
    type: "Model",
    info: "conferences_v1.model",
    virtual: "concrete",
    quality: {
      Complexity: "15.0",
      Coverage: "0.9750000238418579",
    },
  },
  "conferences_v3.model": {
    name: "conferences_v3.model",
    type: "Model",
    info: "conferences_v3.model",
    virtual: "concrete",
    quality: {
      Complexity: "17.0",
      Coverage: "0.9750000238418579",
    },
  },
  "sigcomponents-model1.model": {
    name: "sigcomponents-model1.model",
    type: "Model",
    info: "sigcomponents-model1.model",
    virtual: "concrete",
    quality: {
      Complexity: "4.0",
      Coverage: "0.8888888955116272",
    },
  },
  "sigocmponentsMMv1_example4.model": {
    name: "sigocmponentsMMv1_example4.model",
    type: "Model",
    info: "sigocmponentsMMv1_example4.model",
    virtual: "concrete",
    quality: {
      Complexity: "5.0",
      Coverage: "1.0",
    },
  },
  "conferences_v4.model": {
    name: "conferences_v4.model",
    type: "Model",
    info: "conferences_v4.model",
    virtual: "concrete",
    quality: {
      Complexity: "15.0",
      Coverage: "0.9750000238418579",
    },
  },
  "tasks2_v1.model": {
    name: "tasks2_v1.model",
    type: "Model",
    info: "tasks2_v1.model",
    virtual: "concrete",
    quality: {
      Complexity: "39.0",
      Coverage: "0.9166666865348816",
    },
  },
  "tasks3_v1.model": {
    name: "tasks3_v1.model",
    type: "Model",
    info: "tasks3_v1.model",
    virtual: "concrete",
    quality: {
      Complexity: "32.0",
      Coverage: "0.8499999642372131",
    },
  },
  "sigocmponentsMMv1_example3.model": {
    name: "sigocmponentsMMv1_example3.model",
    type: "Model",
    info: "sigocmponentsMMv1_example3.model",
    virtual: "concrete",
    quality: {
      Complexity: "5.0",
      Coverage: "1.0",
    },
  },
  "sigcomponents-model4.model": {
    name: "sigcomponents-model4.model",
    type: "Model",
    info: "sigcomponents-model4.model",
    virtual: "concrete",
    quality: {
      Complexity: "9.0",
      Coverage: "1.0",
    },
  },
  "sigocmponentsMMv1_example1.model": {
    name: "sigocmponentsMMv1_example1.model",
    type: "Model",
    info: "sigocmponentsMMv1_example1.model",
    virtual: "concrete",
    quality: {
      Complexity: "7.0",
      Coverage: "1.0",
    },
  },
  "conferences1_v1.model": {
    name: "conferences1_v1.model",
    type: "Model",
    info: "conferences1_v1.model",
    virtual: "concrete",
    quality: {
      Complexity: "10.0",
      Coverage: "0.9750000238418579",
    },
  },
  "conferences_v2.model": {
    name: "conferences_v2.model",
    type: "Model",
    info: "conferences_v2.model",
    virtual: "concrete",
    quality: {
      Complexity: "10.0",
      Coverage: "0.9750000238418579",
    },
  },
  "sigocmponentsMMv1_example5.model": {
    name: "sigocmponentsMMv1_example5.model",
    type: "Model",
    info: "sigocmponentsMMv1_example5.model",
    virtual: "concrete",
    quality: {
      Complexity: "6.0",
      Coverage: "1.0",
    },
  },
  "sigcomponents-model2.model": {
    name: "sigcomponents-model2.model",
    type: "Model",
    info: "sigcomponents-model2.model",
    virtual: "concrete",
    quality: {
      Complexity: "7.0",
      Coverage: "1.0",
    },
  },
  "tasksv1_example1.model": {
    name: "tasksv1_example1.model",
    type: "Model",
    info: "tasksv1_example1.model",
    virtual: "concrete",
    quality: {
      Complexity: "13.0",
      Coverage: "0.8611111640930176",
    },
  },
  "conferences4_v1.model": {
    name: "conferences4_v1.model",
    type: "Model",
    info: "conferences4_v1.model",
    virtual: "concrete",
    quality: {
      Complexity: "43.0",
      Coverage: "0.9750000238418579",
    },
  },
  "conferences_v1_example4.model": {
    name: "conferences_v1_example4.model",
    type: "Model",
    info: "conferences_v1_example4.model",
    virtual: "concrete",
    quality: {
      Complexity: "12.0",
      Coverage: "0.9750000238418579",
    },
  },
  "conferences5_v1.model": {
    name: "conferences5_v1.model",
    type: "Model",
    info: "conferences5_v1.model",
    virtual: "concrete",
    quality: {
      Complexity: "48.0",
      Coverage: "0.9750000238418579",
    },
  },
  "task4.model": {
    name: "task4.model",
    type: "Model",
    info: "task4.model",
    virtual: "concrete",
    quality: {
      Complexity: "8.0",
      Coverage: "1.0",
    },
  },
  "fb.model": {
    name: "fb.model",
    type: "Model",
    info: "fb.model",
    virtual: "concrete",
    quality: {
      Complexity: "16.0",
      Coverage: "0.949999988079071",
    },
  },
  "tasksv1_example3.model": {
    name: "tasksv1_example3.model",
    type: "Model",
    info: "tasksv1_example3.model",
    virtual: "concrete",
    quality: {
      Complexity: "10.0",
      Coverage: "0.944444477558136",
    },
  },
  "conferences_v1_example2.model": {
    name: "conferences_v1_example2.model",
    type: "Model",
    info: "conferences_v1_example2.model",
    virtual: "concrete",
    quality: {
      Complexity: "21.0",
      Coverage: "0.9750000238418579",
    },
  },
  "signcomponents2_v1.model": {
    name: "signcomponents2_v1.model",
    type: "Model",
    info: "signcomponents2_v1.model",
    virtual: "concrete",
    quality: {
      Complexity: "9.0",
      Coverage: "1.0",
    },
  },
  "signcomponents3_v1.model": {
    name: "signcomponents3_v1.model",
    type: "Model",
    info: "signcomponents3_v1.model",
    virtual: "concrete",
    quality: {
      Complexity: "15.0",
      Coverage: "1.0",
    },
  },
  "task2.model": {
    name: "task2.model",
    type: "Model",
    info: "task2.model",
    virtual: "concrete",
    quality: {
      Complexity: "11.0",
      Coverage: "0.9166666865348816",
    },
  },
  "tasksv1_example5.model": {
    name: "tasksv1_example5.model",
    type: "Model",
    info: "tasksv1_example5.model",
    virtual: "concrete",
    quality: {
      Complexity: "20.0",
      Coverage: "0.7527778148651123",
    },
  },
  "task5.model": {
    name: "task5.model",
    type: "Model",
    info: "task5.model",
    virtual: "concrete",
    quality: {
      Complexity: "7.0",
      Coverage: "0.6666666865348816",
    },
  },
  "tasksv1_example2.model": {
    name: "tasksv1_example2.model",
    type: "Model",
    info: "tasksv1_example2.model",
    virtual: "concrete",
    quality: {
      Complexity: "14.0",
      Coverage: "0.694444477558136",
    },
  },
  "signcomponents5_v1.model": {
    name: "signcomponents5_v1.model",
    type: "Model",
    info: "signcomponents5_v1.model",
    virtual: "concrete",
    quality: {
      Complexity: "15.0",
      Coverage: "1.0",
    },
  },
  "signcomponents4_v1.model": {
    name: "signcomponents4_v1.model",
    type: "Model",
    info: "signcomponents4_v1.model",
    virtual: "concrete",
    quality: {
      Complexity: "13.0",
      Coverage: "1.0",
    },
  },
  "conferences_v1_example5.model": {
    name: "conferences_v1_example5.model",
    type: "Model",
    info: "conferences_v1_example5.model",
    virtual: "concrete",
    quality: {
      Complexity: "6.0",
      Coverage: "0.7166666388511658",
    },
  },
  "task3.model": {
    name: "task3.model",
    type: "Model",
    info: "task3.model",
    virtual: "concrete",
    quality: {
      Complexity: "22.0",
      Coverage: "0.75",
    },
  },
  "conferences3_v1.model": {
    name: "conferences3_v1.model",
    type: "Model",
    info: "conferences3_v1.model",
    virtual: "concrete",
    quality: {
      Complexity: "31.0",
      Coverage: "0.9750000238418579",
    },
  },
  "conferences2_v1.model": {
    name: "conferences2_v1.model",
    type: "Model",
    info: "conferences2_v1.model",
    virtual: "concrete",
    quality: {
      Complexity: "15.0",
      Coverage: "0.9750000238418579",
    },
  },
  "conferences_v1_example1.model": {
    name: "conferences_v1_example1.model",
    type: "Model",
    info: "conferences_v1_example1.model",
    virtual: "concrete",
    quality: {
      Complexity: "10.0",
      Coverage: "0.9750000238418579",
    },
  },
  "tasksv1_example4.model": {
    name: "tasksv1_example4.model",
    type: "Model",
    info: "tasksv1_example4.model",
    virtual: "concrete",
    quality: {
      Complexity: "7.0",
      Coverage: "0.944444477558136",
    },
  },
  "tasks1_v1.model": {
    name: "tasks1_v1.model",
    type: "Model",
    info: "tasks1_v1.model",
    virtual: "concrete",
    quality: {
      Complexity: "24.0",
      Coverage: "0.9166666865348816",
    },
  },
  "conferences_v1_example3.model": {
    name: "conferences_v1_example3.model",
    type: "Model",
    info: "conferences_v1_example3.model",
    virtual: "concrete",
    quality: {
      Complexity: "10.0",
      Coverage: "0.9750000238418579",
    },
  },
  "task1.model": {
    name: "task1.model",
    type: "Model",
    info: "task1.model",
    virtual: "concrete",
    quality: {
      Complexity: "14.0",
      Coverage: "0.9166666865348816",
    },
  },
};
